# Generated by Django 4.0.2 on 2022-02-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="condition",
            field=models.CharField(
                choices=[
                    ("poor", "Poor"),
                    ("fair", "Fair"),
                    ("good", "Good"),
                    ("excellent", "Excellent"),
                ],
                max_length=1000,
            ),
        ),
    ]
