# Generated by Django 4.0.2 on 2022-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0004_alter_carmodel_asking_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
